<?php
/**
 * Created by PhpStorm.
 * User: InkoHX
 * Date: 2018/12/14
 * Time: 1:04
 */

namespace InkoHX\LevelSystem;

use pocketmine\plugin\PluginBase;

class Core extends PluginBase
{
    public function onLoad()
    {
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    public function onEnable()
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}