<?php
/**
 * Created by PhpStorm.
 * User: InkoHX
 * Date: 2018/12/14
 * Time: 1:04
 */

namespace InkoHX\LevelSystem;

use InkoHX\LeveLibrary\LevelAPI;
use pocketmine\plugin\PluginBase;

class Core extends PluginBase
{
    public function onLoad()
    {
        $this->getLogger()->info('Loading...');
        LevelAPI::init();
        $this->saveDefaultConfig();
    }

    public function onEnable()
    {
        $this->getLogger()->info('
        
§eLLLLLLLLLLL              §b   SSSSSSSSSSSSSSS 
§eL:::::::::L              §b SS:::::::::::::::S
§eL:::::::::L              §bS:::::SSSSSS::::::S
§eLL:::::::LL              §bS:::::S     SSSSSSS
  §eL:::::L                §bS:::::S            
  §eL:::::L                §bS:::::S            
  §eL:::::L                §b S::::SSSS         
  §eL:::::L                §b  SS::::::SSSSS    
  §eL:::::L                §b    SSS::::::::SS  
  §eL:::::L                §b       SSSSSS::::S 
  §eL:::::L                §b            S:::::S
  §eL:::::L         LLLLLL §b            S:::::S
§eLL:::::::LLLLLLLLL:::::L §bSSSSSSS     S:::::S
§eL::::::::::::::::::::::L §bS::::::SSSSSS:::::S
§eL::::::::::::::::::::::L §bS:::::::::::::::SS 
§eLLLLLLLLLLLLLLLLLLLLLLLL §bSSSSSSSSSSSSSSS   
                      
             §7Dev: InkoHX
        
        ');
    }

    public function onDisable()
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }
}